# Generated by Django 5.2.11 on 2026-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
