name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup docker compose
      run: docker compose up -d
    - name: run test
      run: docker compose exec todo_web sh -c "python -m pytest ."
